CREATE SCHEMA IF NOT EXISTS LISTING;
USE LISTING;

CREATE TABLE IF NOT EXISTS COIN_PAIR (
	ID int identity primary key,
	SYMBOL varchar(20),
	BASE_ASSET varchar(20),
	QUOTE_ASSET varchar(20)
);

CREATE TABLE IF NOT EXISTS COIN_PRICE (
	ID BIGINT identity primary key,
	SHORT_DESC varchar(100),
	PRICE DECIMAL,
	UPDATE_TIME TIMESTAMP
);

CREATE TABLE IF NOT EXISTS COIN_CATALOG (
	ID int identity primary key,
	SHORT_DESC varchar(100),
	COIN_PAIR_ID int
);

CREATE TABLE IF NOT EXISTS CURRENCY (
	ID int identity primary key,
	SYMBOL varchar(100),
	NAME varchar(100)
);


CREATE TABLE IF NOT EXISTS CONTEST (
	ID int identity primary key,
	TITLE varchar(100),
	TRADING_AMOUNT DECIMAL,
	CURRENCY_ID int,
	START_DATE TIMESTAMP,
	END_DATE TIMESTAMP,
	LOCK_DATE TIMESTAMP,
	DESCRIPTION varchar(300),
	STATUS varchar(20),
	COIN_CATALOG_ID int
);